Add dunder methods to the Python `Record` class
onecodex/needletail pull request #91
Opened 2024-12-19 15:51 UTC by apcamargo

This PR introduces several dunder methods to the Python `Record` class:

- `__new__`: Constructor that allows the direct creation of `Record` objects:
```py
>>> fasta_record = needletail.Record("SRR1749083.HWI-ST1309F", "NGACTCGTC")
>>> fastq_record = needletail.Record("SRR1749083.HWI-ST1309F", "NGACTCGTC", "#<<BBF/FF")
```
- `__hash__`: Returns an integer hash based on the record's ID, sequence, and quality (if available). This overrides the default `__hash__`, which generates different hashes for identical objects.
- `__eq__`: Compares two `Record` objects by checking if their IDs, sequences, and qualities (if available) are identical. While we could check for equality based on hashes, this would involve additional computation.
- `__len__`: Returns the length of the sequence, similar to BioPython's behavior.
- `__str__`: Returns a string formatted in FASTA/FASTQ style to facilitate writing FASTX files. Currently, sequences are wrapped at 60 characters for FASTA records, though the wrapping can be adjusted.
- `__repr__`: Provides a simple string representation that includes the record ID, a sequence snippet, and the quality string (when available):
```py
>>> needletail.Record("SRR1749083.HWI-ST1309F", "NGACTCGTC")
# Record(id=SRR1749083.HWI-ST1309F, sequence=NGACTCGTC, quality=None)
```
Additionally, is_fasta and is_fastq have been converted to properties.

Test coverage for these methods has not been added yet, but I will implement it if this PR is approved.

2025-01-22 02:30 UTC, audy requested changes

2025-01-22 02:30 UTC, audy commented on src/python.rs
> +            let wrapped_seq = self
I'd prefer unwrapped to be the default. IMO wrapping adds unnecessary bytes and is more difficult to handle with grep, etc.

2025-01-22 02:30 UTC, audy commented on src/python.rs
> +            Ok(format!(">{}\n{}", self.id, wrapped_seq))
I'm on the fence about whether these should end in a newline. BioPython does add a newline and I'm apt to follow convention. Maybe a tie breaker is that a `\n` denotes a record separator while reading a FASTA so it should be present when writing a FASTA record.

2025-01-22 02:30 UTC, audy commented on src/python.rs
>      pub fn is_fasta(&self) -> PyResult<bool> {
I agree that the getters are nicer but for reverse-compatibility's sake I think these should be left as-is.

2025-01-22 02:31 UTC, audy commented
@apcamargo thank you very much! I left some comments. Otherwise, these changes look like great additions to the library and we'd be happy to merge them in.

2025-01-22 20:52 UTC, apcamargo commented
Thanks for the review, @audy! I just pushed commits that address all your comments.

I prefer wrapping since that's how other libraries/tools format FASTAs, and I think users expect it. That said, I’m not too attached to it :)

2025-01-22 21:16 UTC, audy approved these changes

2025-01-22 21:20 UTC, audy commented
@apcamargo thanks for making those changes. Let me know if you're good to merge.

2025-01-23 00:50 UTC, apcamargo commented
@audy I’ve added docstrings to all classes, methods, and functions. The only potential change I’d consider is adding a default value to the `iupac` parameter in both `normalize_seq` and `normalize`.

As for the CI error, would you prefer that I replace the backticks with single quotes (`'`)? I opted for backticks because I’m adhering to [NumPy’s docstring guidelines](https://numpydoc.readthedocs.io/en/latest/format.html#parameters).

2025-01-24 04:29 UTC, apcamargo commented
Also updated `parse_fastx_file` to make it able to take `pathlib.Path` objects, in addition to `str`.

2025-01-24 16:24 UTC, audy commented
@apcamargo Awesome! Do you mind adding some tests?

> The only potential change I’d consider is adding a default value to the iupac parameter in both normalize_seq and normalize.

I support this change but I'm not sure if it should default to `True` or `False`. Thoughts?

2025-01-24 23:09 UTC, apcamargo commented
Apologies, @audy! I had forgotten about the tests.

I've now added tests for all the new functions and methods, and set the default value of `iupac` to `False`.

2025-01-27 18:22 UTC, audy commented on test_python.py
> +    def test_pathlib_path_input(self):
@apcamargo can you add this?

2025-01-27 18:22 UTC, audy commented on test_python.py
> +class RecordClassTestCase(unittest.TestCase):
can you add tests for `str(record)` @apcamargo ?

2025-01-27 18:23 UTC, audy requested changes
See comments

2025-01-27 20:30 UTC, apcamargo commented on test_python.py
> +class RecordClassTestCase(unittest.TestCase):
I think those are already there. In lines 63-68:

```py
    def test_record_str(self):
        self.assertEqual(str(Record("test", "AGCTGATCGA")), ">test\nAGCTGATCGA\n")
        self.assertEqual(
            str(Record("test", "AGCTGATCGA", ";**9;;????")),
            "@test\nAGCTGATCGA\n+\n;**9;;????\n",
        )
```

2025-01-27 20:42 UTC, apcamargo commented
@audy Can you check if your comments were solved?

2025-01-27 20:58 UTC, apcamargo commented
Ah, I see what you mean about `test_pathlib_path_input` now. The purpose of that method in `StrParsingTestCase` was to avoid getting it inherited from `FileParsingTestCase`.

To avoid having an empty method with just `pass`, I flipped things around and made `FileParsingTestCase` inherit from `StrParsingTestCase` instead.

2025-01-28 16:22 UTC, audy approved these changes
Looks great!

2025-01-29 12:10 UTC, apcamargo commented
Thanks, @audy!

2025-01-30 21:28 UTC, audy commented
> What do you think about modifying the normalize method to return a new Record object instead of only applying in-place modifications?

This seems more Pythonic but doesn't match the Rust implementation (it might be clearer for the Rust and Python methods to have the same behavior). So I would maybe add a second method called `.to_normalized_record()` or similar.

> Would it be useful to add a property that returns a list of integers representing quality scores? Alternatively, it could be a method with a parameter to specify the encoding base (64 or 33).

I think that would be useful.

>  I can include this change in this PR or address it in a separate one after this is merged.

I think this PR is good to go and both of these items can be addressed as separate PRs.

2025-02-01 11:53 UTC, apcamargo commented
Agreed. I can work on that once this is merged.

Also, would you consider making a release once this is merged? I'm working on an API that uses needletail and it would be nice to have these features there.

No worries if you plan to have releases only when the Rust library gets updated

2025-02-01 21:00 UTC, audy commented
@apcamargo I can push a release to pypi. May I go ahead and merge?

2025-02-01 21:08 UTC, apcamargo commented
Sure! Thank you!

2025-02-01 21:34 UTC, merged

2025-02-01 22:08 UTC, apcamargo commented
Thanks, @audy!

Just one request: Could you also upload the source to PyPI? I’d like to update the Bioconda recipe to fetch the library from PyPI, and the source code is required for building in Bioconda's CI. I think you just need to include the `--sdist` flag when calling `maturin build`.